apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todo-app/manifests/service.yaml
- todo-app/manifests/configmap.yaml
- todo-app/manifests/ingress.yaml
- todo-app/manifests/statefulset.yaml
- todo-app/manifests/deployment.yaml
- todo-app/manifests/cronjob.yaml
- todo-app/manifests/horizontalpodautoscaler.yaml
images:
  - name: PROJECT/IMAGE
    newName: hpkhanhloc/todo-app:v0.6.21