apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      volumes:
        - name: shared-text
          persistentVolumeClaim:
            claimName: text-claim
      containers:
        - name: pingpong-app
          image: hpkhanhloc/pingpong-application:v0.2
          volumeMounts:
            - name: shared-text
              mountPath: /usr/src/app/files
