apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/configmap.yaml
- manifests/ingress.yaml
- manifests/statefulset.yaml
- manifests/cronjob.yaml
images:
  - name: PROJECT/IMAGE
    newName: hpkhanhloc/todo-app:v0.6.21