apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      containers:
        - name: pingpong-app
          image: hpkhanhloc/pingpong-application:v0.3.11
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 3000
