apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingpong-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pingpong-app-deployment
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50