apiVersion: v1
kind: Service
metadata:
  name: pingpong-postgres-svc
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: pingpong-postgres-app
---
apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
spec:
  type: ClusterIP
  selector:
    app: pingpong-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
