apiVersion: v1
kind: Service
metadata:
  name: pp-postgres-svc
  labels:
    app: pp-postgres
spec:
  ports:
    - port: 5432
      name: pp-web
  clusterIP: None
  selector:
    app: pp-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pp-postgres-ss
spec:
  serviceName: pp-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: pp-postgres
  template:
    metadata:
      labels:
        app: pp-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.0
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - name: pp-web
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
