apiVersion: apps/v1
kind: Deployment
metadata:
  name: string-generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: string-generator
  template:
    metadata:
      labels:
        app: string-generator
    spec:
      containers:
        - name: string-generator
          image: hpkhanhloc/string-generator:1.0
