apiVersion: batch/v1
kind: Job
metadata:
  name: dummysite-controller-dep
spec:
  template:
    metadata:
      labels:
        app: dummysite-controller
    spec:
      serviceAccountName: dummysite-controller-account
      containers:
        - name: dummysite-controller
          image: hpkhanhloc/dummysite-controller:v0.0.39
      restartPolicy: Never